media:
  input: ""
  output: "/"

content:
  - name: data
    label: Site Verileri (Etkinlik, Galeri, Arşiv)
    type: file
    path: data.json
    fields:
      - name: slider
        label: Gösterimdekiler (Ana Slider)
        type: object
        list: true
        fields:
          - name: image
            label: Fotoğraf
            type: image
      - name: etkinlikler
        label: Etkinlikler
        type: object
        list: true
        fields:
          - name: title
            label: Etkinlik Başlığı
            type: string
          - name: date
            label: Tarih ve Saat
            type: string
      - name: arsiv
        label: Arşiv Galerileri
        type: object
        list: true
        fields:
          - name: id
            label: "ID (Boşluksuz İngilizce karakter, örn: yenisergi)"
            type: string
          - name: title
            label: Arşiv Başlığı (Ekranda Görünen)
            type: string
          - name: coverImage
            label: Kapak Fotoğrafı
            type: image
          - name: images
            label: Galeri İçindeki Fotoğraflar
            type: object
            list: true
            fields:
              - name: image
                label: Fotoğraf Seç
                type: image